### PR TITLE
Relax the version requirements for dependencies to make it work better with other modules

### PR DESCRIPTION
**Pull request by exptom**

### CODE REVIEW

**Comment by bschonec** [comment]
Yeah, I need this pull as well.   I'm trying to install freetds on Puppet Server 4.7.0 with:

puppetlabs-stdlib (v4.11.0)
puppetlabs-concat (v1.2.5)

however 'puppet module install tchmnkyz-freetds' fails due to dependencies.

**Comment by exptom** [comment]
I ended up having to reference my fork in the `Puppetfile` as this module appears to be unmaintained now.

**Comment by bschonec** [comment]
Would you share how you did that?  I'm no puppet master...

**Comment by exptom** [comment]
Sure. I use librarian-puppet to manage module installations (which I assume you do?).

In `Puppetfile`:

replace: 
```
mod 'tchmnkyz-freetds','0.0.5'
```
with:
```
mod 'tchmnkyz-freetds',
  :git => 'git://github.com/exptom/freetds.git',
  :ref => 'master'
```

You will probably need to fork the module yourself to change the module versions to support puppet v4 as I am still using v3.

**Comment by tchmnkyz** [comment]
Sorry it took so long. Been a while since i logged into github.

**Comment by exptom** [comment]
@tchmnkyz thanks!

**Pull request merged**
